name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    env:
      PORT: ${{ secrets.PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (backend)
        run: |
          cd phonebook-backend
          npm install

      - name: Check Lint (backend)
        run: |
          cd phonebook-backend
          npm run lint

      - name: Run tests (backend)
        run: |
          cd phonebook-backend
          npm test

      - name: Build (backend)
        run: |
            cd phonebook-backend
            npm run build

      - name: Install dependencies (frontend)
        run: |
          cd phonebook-frontend
          npm install


      - name: Check Lint (frontend)
        run: |
          cd phonebook-frontend
          npm run lint

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Install Playwright dependencies
        run: sudo npx playwright install-deps

      - name: Test (frontend)
        run: |
          cd phonebook-frontend
          npm test

      - name: e2e tests (frontend)
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:4173
          working-directory: phonebook-frontend